export const USER_CREATED = 'USER_CREATED';
export const USER_NONE_EMAIL = 'USER_NONE_EMAIL';
export const USER_MISMATCH_PASSWORD = 'USER_MISMATCH_PASSWORD';
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const TRANSACTION_POST_SUCCESS = 'TRANSACTION_POST_SUCCESS';
export const CATEGORY_ALL_GET_SUCCESS = 'CATEGORY_ALL_GET_SUCCESS';
