export const USER_STATUS = {
  USER_CREATED: 'USER_CREATED',
  USER_NONE_EMAIL: 'USER_NONE_EMAIL',
  USER_MISMATCH_PASSWORD: 'USER_MISMATCH_PASSWORD',
  USER_LOGIN_SUCCESS: 'USER_LOGIN_SUCCESS',
} as const;
